# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "register app"
  lane :register_app do
    produce(
      app_name: 'LmwnAssigmentCoinranking',
    )
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :get_dev_certs do
    cert(
      development: true
    )
    sigh(
      development: true,
      force: true
    )
  end

  lane :sync_all_developmnet do 
    sync_device_info
    match(type: "development")
  end

  lane :sync_device_info do
    register_devices(
      # device: {
      #   "Supawat" => "00008110-000205E40E03801E"
      # }
      devices_file: "fastlane/Devicefile"
    )
  end

  lane :beta do
    cocoapods(
      # clean_install: true,
      # podfile: "./Podfile"
    )
    increment_build_number()
    match(type: "appstore")
   
    gym(scheme: "Coinranking", workspace: "Coinranking.xcworkspace", export_method: "app-store", configuration: "Release", clean: true, output_directory: "build")

    # capture_screenshots

    testflight(ipa: "build/Coinranking.ipa", skip_waiting_for_build_processing: true)
    
    clean_build_artifacts
  end

end
